//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfc.TestDataCollection
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIBackInfo", Namespace="http://tempuri.org/")]
    public partial class APIBackInfo : object
    {
        
        private string HeaderField;
        
        private string BodyField;
        
        private string ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sfc.TestDataCollection.TestDataCollectionSoap")]
    public interface TestDataCollectionSoap
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Sfc.TestDataCollection.HelloWorldResponse HelloWorld(Sfc.TestDataCollection.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.HelloWorldResponse> HelloWorldAsync(Sfc.TestDataCollection.HelloWorldRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 TestResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        Sfc.TestDataCollection.TestResponse Test(Sfc.TestDataCollection.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.TestResponse> TestAsync(Sfc.TestDataCollection.TestRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 lotNo 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondLotNoAndSn", ReplyAction="*")]
        Sfc.TestDataCollection.BondLotNoAndSnResponse BondLotNoAndSn(Sfc.TestDataCollection.BondLotNoAndSnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondLotNoAndSn", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.BondLotNoAndSnResponse> BondLotNoAndSnAsync(Sfc.TestDataCollection.BondLotNoAndSnRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 lotNo 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondLotNoAndSnOld", ReplyAction="*")]
        Sfc.TestDataCollection.BondLotNoAndSnOldResponse BondLotNoAndSnOld(Sfc.TestDataCollection.BondLotNoAndSnOldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondLotNoAndSnOld", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.BondLotNoAndSnOldResponse> BondLotNoAndSnOldAsync(Sfc.TestDataCollection.BondLotNoAndSnOldRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 dataString 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EndTestDataTransfer", ReplyAction="*")]
        Sfc.TestDataCollection.EndTestDataTransferResponse EndTestDataTransfer(Sfc.TestDataCollection.EndTestDataTransferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EndTestDataTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.EndTestDataTransferResponse> EndTestDataTransferAsync(Sfc.TestDataCollection.EndTestDataTransferRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 sn 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondSensorId", ReplyAction="*")]
        Sfc.TestDataCollection.BondSensorIdResponse BondSensorId(Sfc.TestDataCollection.BondSensorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondSensorId", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.BondSensorIdResponse> BondSensorIdAsync(Sfc.TestDataCollection.BondSensorIdRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 sensorId 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidIsComplete", ReplyAction="*")]
        Sfc.TestDataCollection.ValidIsCompleteResponse ValidIsComplete(Sfc.TestDataCollection.ValidIsCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidIsComplete", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.ValidIsCompleteResponse> ValidIsCompleteAsync(Sfc.TestDataCollection.ValidIsCompleteRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 sensorId 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidIsCompleteNew", ReplyAction="*")]
        Sfc.TestDataCollection.ValidIsCompleteNewResponse ValidIsCompleteNew(Sfc.TestDataCollection.ValidIsCompleteNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidIsCompleteNew", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.ValidIsCompleteNewResponse> ValidIsCompleteNewAsync(Sfc.TestDataCollection.ValidIsCompleteNewRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 testData 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataStorage", ReplyAction="*")]
        Sfc.TestDataCollection.TestDataStorageResponse TestDataStorage(Sfc.TestDataCollection.TestDataStorageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataStorage", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.TestDataStorageResponse> TestDataStorageAsync(Sfc.TestDataCollection.TestDataStorageRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 testData 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataStorageTest", ReplyAction="*")]
        Sfc.TestDataCollection.TestDataStorageTestResponse TestDataStorageTest(Sfc.TestDataCollection.TestDataStorageTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataStorageTest", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.TestDataStorageTestResponse> TestDataStorageTestAsync(Sfc.TestDataCollection.TestDataStorageTestRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 GetCraftInfoResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCraftInfo", ReplyAction="*")]
        Sfc.TestDataCollection.GetCraftInfoResponse GetCraftInfo(Sfc.TestDataCollection.GetCraftInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCraftInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.GetCraftInfoResponse> GetCraftInfoAsync(Sfc.TestDataCollection.GetCraftInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(Sfc.TestDataCollection.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(Sfc.TestDataCollection.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.TestRequestBody Body;
        
        public TestRequest()
        {
        }
        
        public TestRequest(Sfc.TestDataCollection.TestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody
    {
        
        public TestRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.TestResponseBody Body;
        
        public TestResponse()
        {
        }
        
        public TestResponse(Sfc.TestDataCollection.TestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo TestResult;
        
        public TestResponseBody()
        {
        }
        
        public TestResponseBody(Sfc.TestDataCollection.APIBackInfo TestResult)
        {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondLotNoAndSnRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondLotNoAndSn", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.BondLotNoAndSnRequestBody Body;
        
        public BondLotNoAndSnRequest()
        {
        }
        
        public BondLotNoAndSnRequest(Sfc.TestDataCollection.BondLotNoAndSnRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondLotNoAndSnRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lotNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedure;
        
        public BondLotNoAndSnRequestBody()
        {
        }
        
        public BondLotNoAndSnRequestBody(string lotNo, string sn, string procedure)
        {
            this.lotNo = lotNo;
            this.sn = sn;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondLotNoAndSnResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondLotNoAndSnResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.BondLotNoAndSnResponseBody Body;
        
        public BondLotNoAndSnResponse()
        {
        }
        
        public BondLotNoAndSnResponse(Sfc.TestDataCollection.BondLotNoAndSnResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondLotNoAndSnResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo BondLotNoAndSnResult;
        
        public BondLotNoAndSnResponseBody()
        {
        }
        
        public BondLotNoAndSnResponseBody(Sfc.TestDataCollection.APIBackInfo BondLotNoAndSnResult)
        {
            this.BondLotNoAndSnResult = BondLotNoAndSnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondLotNoAndSnOldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondLotNoAndSnOld", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.BondLotNoAndSnOldRequestBody Body;
        
        public BondLotNoAndSnOldRequest()
        {
        }
        
        public BondLotNoAndSnOldRequest(Sfc.TestDataCollection.BondLotNoAndSnOldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondLotNoAndSnOldRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lotNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedure;
        
        public BondLotNoAndSnOldRequestBody()
        {
        }
        
        public BondLotNoAndSnOldRequestBody(string lotNo, string sn, string procedure)
        {
            this.lotNo = lotNo;
            this.sn = sn;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondLotNoAndSnOldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondLotNoAndSnOldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.BondLotNoAndSnOldResponseBody Body;
        
        public BondLotNoAndSnOldResponse()
        {
        }
        
        public BondLotNoAndSnOldResponse(Sfc.TestDataCollection.BondLotNoAndSnOldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondLotNoAndSnOldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo BondLotNoAndSnOldResult;
        
        public BondLotNoAndSnOldResponseBody()
        {
        }
        
        public BondLotNoAndSnOldResponseBody(Sfc.TestDataCollection.APIBackInfo BondLotNoAndSnOldResult)
        {
            this.BondLotNoAndSnOldResult = BondLotNoAndSnOldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EndTestDataTransferRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EndTestDataTransfer", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.EndTestDataTransferRequestBody Body;
        
        public EndTestDataTransferRequest()
        {
        }
        
        public EndTestDataTransferRequest(Sfc.TestDataCollection.EndTestDataTransferRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EndTestDataTransferRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int type;
        
        public EndTestDataTransferRequestBody()
        {
        }
        
        public EndTestDataTransferRequestBody(string dataString, int type)
        {
            this.dataString = dataString;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EndTestDataTransferResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EndTestDataTransferResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.EndTestDataTransferResponseBody Body;
        
        public EndTestDataTransferResponse()
        {
        }
        
        public EndTestDataTransferResponse(Sfc.TestDataCollection.EndTestDataTransferResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EndTestDataTransferResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo EndTestDataTransferResult;
        
        public EndTestDataTransferResponseBody()
        {
        }
        
        public EndTestDataTransferResponseBody(Sfc.TestDataCollection.APIBackInfo EndTestDataTransferResult)
        {
            this.EndTestDataTransferResult = EndTestDataTransferResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondSensorIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondSensorId", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.BondSensorIdRequestBody Body;
        
        public BondSensorIdRequest()
        {
        }
        
        public BondSensorIdRequest(Sfc.TestDataCollection.BondSensorIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondSensorIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sensorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedure;
        
        public BondSensorIdRequestBody()
        {
        }
        
        public BondSensorIdRequestBody(string sn, string sensorId, string procedure)
        {
            this.sn = sn;
            this.sensorId = sensorId;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondSensorIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondSensorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.BondSensorIdResponseBody Body;
        
        public BondSensorIdResponse()
        {
        }
        
        public BondSensorIdResponse(Sfc.TestDataCollection.BondSensorIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondSensorIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo BondSensorIdResult;
        
        public BondSensorIdResponseBody()
        {
        }
        
        public BondSensorIdResponseBody(Sfc.TestDataCollection.APIBackInfo BondSensorIdResult)
        {
            this.BondSensorIdResult = BondSensorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidIsCompleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidIsComplete", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.ValidIsCompleteRequestBody Body;
        
        public ValidIsCompleteRequest()
        {
        }
        
        public ValidIsCompleteRequest(Sfc.TestDataCollection.ValidIsCompleteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidIsCompleteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sensorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string procedure;
        
        public ValidIsCompleteRequestBody()
        {
        }
        
        public ValidIsCompleteRequestBody(string sensorId, string procedure)
        {
            this.sensorId = sensorId;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidIsCompleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidIsCompleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.ValidIsCompleteResponseBody Body;
        
        public ValidIsCompleteResponse()
        {
        }
        
        public ValidIsCompleteResponse(Sfc.TestDataCollection.ValidIsCompleteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidIsCompleteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo ValidIsCompleteResult;
        
        public ValidIsCompleteResponseBody()
        {
        }
        
        public ValidIsCompleteResponseBody(Sfc.TestDataCollection.APIBackInfo ValidIsCompleteResult)
        {
            this.ValidIsCompleteResult = ValidIsCompleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidIsCompleteNewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidIsCompleteNew", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.ValidIsCompleteNewRequestBody Body;
        
        public ValidIsCompleteNewRequest()
        {
        }
        
        public ValidIsCompleteNewRequest(Sfc.TestDataCollection.ValidIsCompleteNewRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidIsCompleteNewRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sensorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string procedure;
        
        public ValidIsCompleteNewRequestBody()
        {
        }
        
        public ValidIsCompleteNewRequestBody(string sensorId, string procedure)
        {
            this.sensorId = sensorId;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidIsCompleteNewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidIsCompleteNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.ValidIsCompleteNewResponseBody Body;
        
        public ValidIsCompleteNewResponse()
        {
        }
        
        public ValidIsCompleteNewResponse(Sfc.TestDataCollection.ValidIsCompleteNewResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidIsCompleteNewResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo ValidIsCompleteNewResult;
        
        public ValidIsCompleteNewResponseBody()
        {
        }
        
        public ValidIsCompleteNewResponseBody(Sfc.TestDataCollection.APIBackInfo ValidIsCompleteNewResult)
        {
            this.ValidIsCompleteNewResult = ValidIsCompleteNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDataStorageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDataStorage", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.TestDataStorageRequestBody Body;
        
        public TestDataStorageRequest()
        {
        }
        
        public TestDataStorageRequest(Sfc.TestDataCollection.TestDataStorageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataStorageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sensorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string finallyResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string badCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string equipmentId;
        
        public TestDataStorageRequestBody()
        {
        }
        
        public TestDataStorageRequestBody(string testData, string sensorId, string procedure, string finallyResult, string badCode, string equipmentId)
        {
            this.testData = testData;
            this.sensorId = sensorId;
            this.procedure = procedure;
            this.finallyResult = finallyResult;
            this.badCode = badCode;
            this.equipmentId = equipmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDataStorageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDataStorageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.TestDataStorageResponseBody Body;
        
        public TestDataStorageResponse()
        {
        }
        
        public TestDataStorageResponse(Sfc.TestDataCollection.TestDataStorageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataStorageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo TestDataStorageResult;
        
        public TestDataStorageResponseBody()
        {
        }
        
        public TestDataStorageResponseBody(Sfc.TestDataCollection.APIBackInfo TestDataStorageResult)
        {
            this.TestDataStorageResult = TestDataStorageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDataStorageTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDataStorageTest", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.TestDataStorageTestRequestBody Body;
        
        public TestDataStorageTestRequest()
        {
        }
        
        public TestDataStorageTestRequest(Sfc.TestDataCollection.TestDataStorageTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataStorageTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testData;
        
        public TestDataStorageTestRequestBody()
        {
        }
        
        public TestDataStorageTestRequestBody(string testData)
        {
            this.testData = testData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDataStorageTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDataStorageTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.TestDataStorageTestResponseBody Body;
        
        public TestDataStorageTestResponse()
        {
        }
        
        public TestDataStorageTestResponse(Sfc.TestDataCollection.TestDataStorageTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataStorageTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo TestDataStorageTestResult;
        
        public TestDataStorageTestResponseBody()
        {
        }
        
        public TestDataStorageTestResponseBody(Sfc.TestDataCollection.APIBackInfo TestDataStorageTestResult)
        {
            this.TestDataStorageTestResult = TestDataStorageTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCraftInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCraftInfo", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.GetCraftInfoRequestBody Body;
        
        public GetCraftInfoRequest()
        {
        }
        
        public GetCraftInfoRequest(Sfc.TestDataCollection.GetCraftInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCraftInfoRequestBody
    {
        
        public GetCraftInfoRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCraftInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCraftInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sfc.TestDataCollection.GetCraftInfoResponseBody Body;
        
        public GetCraftInfoResponse()
        {
        }
        
        public GetCraftInfoResponse(Sfc.TestDataCollection.GetCraftInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCraftInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sfc.TestDataCollection.APIBackInfo GetCraftInfoResult;
        
        public GetCraftInfoResponseBody()
        {
        }
        
        public GetCraftInfoResponseBody(Sfc.TestDataCollection.APIBackInfo GetCraftInfoResult)
        {
            this.GetCraftInfoResult = GetCraftInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TestDataCollectionSoapChannel : Sfc.TestDataCollection.TestDataCollectionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TestDataCollectionSoapClient : System.ServiceModel.ClientBase<Sfc.TestDataCollection.TestDataCollectionSoap>, Sfc.TestDataCollection.TestDataCollectionSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TestDataCollectionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TestDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), TestDataCollectionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestDataCollectionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TestDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestDataCollectionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TestDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestDataCollectionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.HelloWorldResponse Sfc.TestDataCollection.TestDataCollectionSoap.HelloWorld(Sfc.TestDataCollection.HelloWorldRequest request)
        {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld()
        {
            Sfc.TestDataCollection.HelloWorldRequest inValue = new Sfc.TestDataCollection.HelloWorldRequest();
            inValue.Body = new Sfc.TestDataCollection.HelloWorldRequestBody();
            Sfc.TestDataCollection.HelloWorldResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.HelloWorldResponse> Sfc.TestDataCollection.TestDataCollectionSoap.HelloWorldAsync(Sfc.TestDataCollection.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.HelloWorldResponse> HelloWorldAsync()
        {
            Sfc.TestDataCollection.HelloWorldRequest inValue = new Sfc.TestDataCollection.HelloWorldRequest();
            inValue.Body = new Sfc.TestDataCollection.HelloWorldRequestBody();
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.TestResponse Sfc.TestDataCollection.TestDataCollectionSoap.Test(Sfc.TestDataCollection.TestRequest request)
        {
            return base.Channel.Test(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo Test()
        {
            Sfc.TestDataCollection.TestRequest inValue = new Sfc.TestDataCollection.TestRequest();
            inValue.Body = new Sfc.TestDataCollection.TestRequestBody();
            Sfc.TestDataCollection.TestResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.TestResponse> Sfc.TestDataCollection.TestDataCollectionSoap.TestAsync(Sfc.TestDataCollection.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.TestResponse> TestAsync()
        {
            Sfc.TestDataCollection.TestRequest inValue = new Sfc.TestDataCollection.TestRequest();
            inValue.Body = new Sfc.TestDataCollection.TestRequestBody();
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.BondLotNoAndSnResponse Sfc.TestDataCollection.TestDataCollectionSoap.BondLotNoAndSn(Sfc.TestDataCollection.BondLotNoAndSnRequest request)
        {
            return base.Channel.BondLotNoAndSn(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo BondLotNoAndSn(string lotNo, string sn, string procedure)
        {
            Sfc.TestDataCollection.BondLotNoAndSnRequest inValue = new Sfc.TestDataCollection.BondLotNoAndSnRequest();
            inValue.Body = new Sfc.TestDataCollection.BondLotNoAndSnRequestBody();
            inValue.Body.lotNo = lotNo;
            inValue.Body.sn = sn;
            inValue.Body.procedure = procedure;
            Sfc.TestDataCollection.BondLotNoAndSnResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).BondLotNoAndSn(inValue);
            return retVal.Body.BondLotNoAndSnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.BondLotNoAndSnResponse> Sfc.TestDataCollection.TestDataCollectionSoap.BondLotNoAndSnAsync(Sfc.TestDataCollection.BondLotNoAndSnRequest request)
        {
            return base.Channel.BondLotNoAndSnAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.BondLotNoAndSnResponse> BondLotNoAndSnAsync(string lotNo, string sn, string procedure)
        {
            Sfc.TestDataCollection.BondLotNoAndSnRequest inValue = new Sfc.TestDataCollection.BondLotNoAndSnRequest();
            inValue.Body = new Sfc.TestDataCollection.BondLotNoAndSnRequestBody();
            inValue.Body.lotNo = lotNo;
            inValue.Body.sn = sn;
            inValue.Body.procedure = procedure;
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).BondLotNoAndSnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.BondLotNoAndSnOldResponse Sfc.TestDataCollection.TestDataCollectionSoap.BondLotNoAndSnOld(Sfc.TestDataCollection.BondLotNoAndSnOldRequest request)
        {
            return base.Channel.BondLotNoAndSnOld(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo BondLotNoAndSnOld(string lotNo, string sn, string procedure)
        {
            Sfc.TestDataCollection.BondLotNoAndSnOldRequest inValue = new Sfc.TestDataCollection.BondLotNoAndSnOldRequest();
            inValue.Body = new Sfc.TestDataCollection.BondLotNoAndSnOldRequestBody();
            inValue.Body.lotNo = lotNo;
            inValue.Body.sn = sn;
            inValue.Body.procedure = procedure;
            Sfc.TestDataCollection.BondLotNoAndSnOldResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).BondLotNoAndSnOld(inValue);
            return retVal.Body.BondLotNoAndSnOldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.BondLotNoAndSnOldResponse> Sfc.TestDataCollection.TestDataCollectionSoap.BondLotNoAndSnOldAsync(Sfc.TestDataCollection.BondLotNoAndSnOldRequest request)
        {
            return base.Channel.BondLotNoAndSnOldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.BondLotNoAndSnOldResponse> BondLotNoAndSnOldAsync(string lotNo, string sn, string procedure)
        {
            Sfc.TestDataCollection.BondLotNoAndSnOldRequest inValue = new Sfc.TestDataCollection.BondLotNoAndSnOldRequest();
            inValue.Body = new Sfc.TestDataCollection.BondLotNoAndSnOldRequestBody();
            inValue.Body.lotNo = lotNo;
            inValue.Body.sn = sn;
            inValue.Body.procedure = procedure;
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).BondLotNoAndSnOldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.EndTestDataTransferResponse Sfc.TestDataCollection.TestDataCollectionSoap.EndTestDataTransfer(Sfc.TestDataCollection.EndTestDataTransferRequest request)
        {
            return base.Channel.EndTestDataTransfer(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo EndTestDataTransfer(string dataString, int type)
        {
            Sfc.TestDataCollection.EndTestDataTransferRequest inValue = new Sfc.TestDataCollection.EndTestDataTransferRequest();
            inValue.Body = new Sfc.TestDataCollection.EndTestDataTransferRequestBody();
            inValue.Body.dataString = dataString;
            inValue.Body.type = type;
            Sfc.TestDataCollection.EndTestDataTransferResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).EndTestDataTransfer(inValue);
            return retVal.Body.EndTestDataTransferResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.EndTestDataTransferResponse> Sfc.TestDataCollection.TestDataCollectionSoap.EndTestDataTransferAsync(Sfc.TestDataCollection.EndTestDataTransferRequest request)
        {
            return base.Channel.EndTestDataTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.EndTestDataTransferResponse> EndTestDataTransferAsync(string dataString, int type)
        {
            Sfc.TestDataCollection.EndTestDataTransferRequest inValue = new Sfc.TestDataCollection.EndTestDataTransferRequest();
            inValue.Body = new Sfc.TestDataCollection.EndTestDataTransferRequestBody();
            inValue.Body.dataString = dataString;
            inValue.Body.type = type;
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).EndTestDataTransferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.BondSensorIdResponse Sfc.TestDataCollection.TestDataCollectionSoap.BondSensorId(Sfc.TestDataCollection.BondSensorIdRequest request)
        {
            return base.Channel.BondSensorId(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo BondSensorId(string sn, string sensorId, string procedure)
        {
            Sfc.TestDataCollection.BondSensorIdRequest inValue = new Sfc.TestDataCollection.BondSensorIdRequest();
            inValue.Body = new Sfc.TestDataCollection.BondSensorIdRequestBody();
            inValue.Body.sn = sn;
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            Sfc.TestDataCollection.BondSensorIdResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).BondSensorId(inValue);
            return retVal.Body.BondSensorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.BondSensorIdResponse> Sfc.TestDataCollection.TestDataCollectionSoap.BondSensorIdAsync(Sfc.TestDataCollection.BondSensorIdRequest request)
        {
            return base.Channel.BondSensorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.BondSensorIdResponse> BondSensorIdAsync(string sn, string sensorId, string procedure)
        {
            Sfc.TestDataCollection.BondSensorIdRequest inValue = new Sfc.TestDataCollection.BondSensorIdRequest();
            inValue.Body = new Sfc.TestDataCollection.BondSensorIdRequestBody();
            inValue.Body.sn = sn;
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).BondSensorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.ValidIsCompleteResponse Sfc.TestDataCollection.TestDataCollectionSoap.ValidIsComplete(Sfc.TestDataCollection.ValidIsCompleteRequest request)
        {
            return base.Channel.ValidIsComplete(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo ValidIsComplete(string sensorId, string procedure)
        {
            Sfc.TestDataCollection.ValidIsCompleteRequest inValue = new Sfc.TestDataCollection.ValidIsCompleteRequest();
            inValue.Body = new Sfc.TestDataCollection.ValidIsCompleteRequestBody();
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            Sfc.TestDataCollection.ValidIsCompleteResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).ValidIsComplete(inValue);
            return retVal.Body.ValidIsCompleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.ValidIsCompleteResponse> Sfc.TestDataCollection.TestDataCollectionSoap.ValidIsCompleteAsync(Sfc.TestDataCollection.ValidIsCompleteRequest request)
        {
            return base.Channel.ValidIsCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.ValidIsCompleteResponse> ValidIsCompleteAsync(string sensorId, string procedure)
        {
            Sfc.TestDataCollection.ValidIsCompleteRequest inValue = new Sfc.TestDataCollection.ValidIsCompleteRequest();
            inValue.Body = new Sfc.TestDataCollection.ValidIsCompleteRequestBody();
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).ValidIsCompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.ValidIsCompleteNewResponse Sfc.TestDataCollection.TestDataCollectionSoap.ValidIsCompleteNew(Sfc.TestDataCollection.ValidIsCompleteNewRequest request)
        {
            return base.Channel.ValidIsCompleteNew(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo ValidIsCompleteNew(string sensorId, string procedure)
        {
            Sfc.TestDataCollection.ValidIsCompleteNewRequest inValue = new Sfc.TestDataCollection.ValidIsCompleteNewRequest();
            inValue.Body = new Sfc.TestDataCollection.ValidIsCompleteNewRequestBody();
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            Sfc.TestDataCollection.ValidIsCompleteNewResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).ValidIsCompleteNew(inValue);
            return retVal.Body.ValidIsCompleteNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.ValidIsCompleteNewResponse> Sfc.TestDataCollection.TestDataCollectionSoap.ValidIsCompleteNewAsync(Sfc.TestDataCollection.ValidIsCompleteNewRequest request)
        {
            return base.Channel.ValidIsCompleteNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.ValidIsCompleteNewResponse> ValidIsCompleteNewAsync(string sensorId, string procedure)
        {
            Sfc.TestDataCollection.ValidIsCompleteNewRequest inValue = new Sfc.TestDataCollection.ValidIsCompleteNewRequest();
            inValue.Body = new Sfc.TestDataCollection.ValidIsCompleteNewRequestBody();
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).ValidIsCompleteNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.TestDataStorageResponse Sfc.TestDataCollection.TestDataCollectionSoap.TestDataStorage(Sfc.TestDataCollection.TestDataStorageRequest request)
        {
            return base.Channel.TestDataStorage(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo TestDataStorage(string testData, string sensorId, string procedure, string finallyResult, string badCode, string equipmentId)
        {
            Sfc.TestDataCollection.TestDataStorageRequest inValue = new Sfc.TestDataCollection.TestDataStorageRequest();
            inValue.Body = new Sfc.TestDataCollection.TestDataStorageRequestBody();
            inValue.Body.testData = testData;
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            inValue.Body.finallyResult = finallyResult;
            inValue.Body.badCode = badCode;
            inValue.Body.equipmentId = equipmentId;
            Sfc.TestDataCollection.TestDataStorageResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).TestDataStorage(inValue);
            return retVal.Body.TestDataStorageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.TestDataStorageResponse> Sfc.TestDataCollection.TestDataCollectionSoap.TestDataStorageAsync(Sfc.TestDataCollection.TestDataStorageRequest request)
        {
            return base.Channel.TestDataStorageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.TestDataStorageResponse> TestDataStorageAsync(string testData, string sensorId, string procedure, string finallyResult, string badCode, string equipmentId)
        {
            Sfc.TestDataCollection.TestDataStorageRequest inValue = new Sfc.TestDataCollection.TestDataStorageRequest();
            inValue.Body = new Sfc.TestDataCollection.TestDataStorageRequestBody();
            inValue.Body.testData = testData;
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            inValue.Body.finallyResult = finallyResult;
            inValue.Body.badCode = badCode;
            inValue.Body.equipmentId = equipmentId;
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).TestDataStorageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.TestDataStorageTestResponse Sfc.TestDataCollection.TestDataCollectionSoap.TestDataStorageTest(Sfc.TestDataCollection.TestDataStorageTestRequest request)
        {
            return base.Channel.TestDataStorageTest(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo TestDataStorageTest(string testData)
        {
            Sfc.TestDataCollection.TestDataStorageTestRequest inValue = new Sfc.TestDataCollection.TestDataStorageTestRequest();
            inValue.Body = new Sfc.TestDataCollection.TestDataStorageTestRequestBody();
            inValue.Body.testData = testData;
            Sfc.TestDataCollection.TestDataStorageTestResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).TestDataStorageTest(inValue);
            return retVal.Body.TestDataStorageTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.TestDataStorageTestResponse> Sfc.TestDataCollection.TestDataCollectionSoap.TestDataStorageTestAsync(Sfc.TestDataCollection.TestDataStorageTestRequest request)
        {
            return base.Channel.TestDataStorageTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.TestDataStorageTestResponse> TestDataStorageTestAsync(string testData)
        {
            Sfc.TestDataCollection.TestDataStorageTestRequest inValue = new Sfc.TestDataCollection.TestDataStorageTestRequest();
            inValue.Body = new Sfc.TestDataCollection.TestDataStorageTestRequestBody();
            inValue.Body.testData = testData;
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).TestDataStorageTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sfc.TestDataCollection.GetCraftInfoResponse Sfc.TestDataCollection.TestDataCollectionSoap.GetCraftInfo(Sfc.TestDataCollection.GetCraftInfoRequest request)
        {
            return base.Channel.GetCraftInfo(request);
        }
        
        public Sfc.TestDataCollection.APIBackInfo GetCraftInfo()
        {
            Sfc.TestDataCollection.GetCraftInfoRequest inValue = new Sfc.TestDataCollection.GetCraftInfoRequest();
            inValue.Body = new Sfc.TestDataCollection.GetCraftInfoRequestBody();
            Sfc.TestDataCollection.GetCraftInfoResponse retVal = ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).GetCraftInfo(inValue);
            return retVal.Body.GetCraftInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sfc.TestDataCollection.GetCraftInfoResponse> Sfc.TestDataCollection.TestDataCollectionSoap.GetCraftInfoAsync(Sfc.TestDataCollection.GetCraftInfoRequest request)
        {
            return base.Channel.GetCraftInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sfc.TestDataCollection.GetCraftInfoResponse> GetCraftInfoAsync()
        {
            Sfc.TestDataCollection.GetCraftInfoRequest inValue = new Sfc.TestDataCollection.GetCraftInfoRequest();
            inValue.Body = new Sfc.TestDataCollection.GetCraftInfoRequestBody();
            return ((Sfc.TestDataCollection.TestDataCollectionSoap)(this)).GetCraftInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TestDataCollectionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TestDataCollectionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TestDataCollectionSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://sfc.nnmz.aacoptics.com:8888/WebService/TestDataCollection.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TestDataCollectionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://sfc.nnmz.aacoptics.com:8888/WebService/TestDataCollection.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TestDataCollectionSoap,
            
            TestDataCollectionSoap12,
        }
    }
}
