//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIBackInfo", Namespace="http://tempuri.org/")]
    public partial class APIBackInfo : object
    {
        
        private string HeaderField;
        
        private string BodyField;
        
        private string ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TestDataCollectionSoap")]
    public interface TestDataCollectionSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.HelloWorldResponse> HelloWorldAsync(ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TestResponse> TestAsync(ServiceReference1.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondLotNoAndSn", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.BondLotNoAndSnResponse> BondLotNoAndSnAsync(ServiceReference1.BondLotNoAndSnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondLotNoAndSnOld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.BondLotNoAndSnOldResponse> BondLotNoAndSnOldAsync(ServiceReference1.BondLotNoAndSnOldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EndTestDataTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.EndTestDataTransferResponse> EndTestDataTransferAsync(ServiceReference1.EndTestDataTransferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BondSensorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.BondSensorIdResponse> BondSensorIdAsync(ServiceReference1.BondSensorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidIsComplete", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ValidIsCompleteResponse> ValidIsCompleteAsync(ServiceReference1.ValidIsCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidIsCompleteNew", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ValidIsCompleteNewResponse> ValidIsCompleteNewAsync(ServiceReference1.ValidIsCompleteNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataStorage", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TestDataStorageResponse> TestDataStorageAsync(ServiceReference1.TestDataStorageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDataStorageTest", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TestDataStorageTestResponse> TestDataStorageTestAsync(ServiceReference1.TestDataStorageTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCraftInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetCraftInfoResponse> GetCraftInfoAsync(ServiceReference1.GetCraftInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(ServiceReference1.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(ServiceReference1.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.TestRequestBody Body;
        
        public TestRequest()
        {
        }
        
        public TestRequest(ServiceReference1.TestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody
    {
        
        public TestRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.TestResponseBody Body;
        
        public TestResponse()
        {
        }
        
        public TestResponse(ServiceReference1.TestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo TestResult;
        
        public TestResponseBody()
        {
        }
        
        public TestResponseBody(ServiceReference1.APIBackInfo TestResult)
        {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondLotNoAndSnRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondLotNoAndSn", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.BondLotNoAndSnRequestBody Body;
        
        public BondLotNoAndSnRequest()
        {
        }
        
        public BondLotNoAndSnRequest(ServiceReference1.BondLotNoAndSnRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondLotNoAndSnRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lotNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedure;
        
        public BondLotNoAndSnRequestBody()
        {
        }
        
        public BondLotNoAndSnRequestBody(string lotNo, string sn, string procedure)
        {
            this.lotNo = lotNo;
            this.sn = sn;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondLotNoAndSnResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondLotNoAndSnResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.BondLotNoAndSnResponseBody Body;
        
        public BondLotNoAndSnResponse()
        {
        }
        
        public BondLotNoAndSnResponse(ServiceReference1.BondLotNoAndSnResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondLotNoAndSnResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo BondLotNoAndSnResult;
        
        public BondLotNoAndSnResponseBody()
        {
        }
        
        public BondLotNoAndSnResponseBody(ServiceReference1.APIBackInfo BondLotNoAndSnResult)
        {
            this.BondLotNoAndSnResult = BondLotNoAndSnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondLotNoAndSnOldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondLotNoAndSnOld", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.BondLotNoAndSnOldRequestBody Body;
        
        public BondLotNoAndSnOldRequest()
        {
        }
        
        public BondLotNoAndSnOldRequest(ServiceReference1.BondLotNoAndSnOldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondLotNoAndSnOldRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lotNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedure;
        
        public BondLotNoAndSnOldRequestBody()
        {
        }
        
        public BondLotNoAndSnOldRequestBody(string lotNo, string sn, string procedure)
        {
            this.lotNo = lotNo;
            this.sn = sn;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondLotNoAndSnOldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondLotNoAndSnOldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.BondLotNoAndSnOldResponseBody Body;
        
        public BondLotNoAndSnOldResponse()
        {
        }
        
        public BondLotNoAndSnOldResponse(ServiceReference1.BondLotNoAndSnOldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondLotNoAndSnOldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo BondLotNoAndSnOldResult;
        
        public BondLotNoAndSnOldResponseBody()
        {
        }
        
        public BondLotNoAndSnOldResponseBody(ServiceReference1.APIBackInfo BondLotNoAndSnOldResult)
        {
            this.BondLotNoAndSnOldResult = BondLotNoAndSnOldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EndTestDataTransferRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EndTestDataTransfer", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.EndTestDataTransferRequestBody Body;
        
        public EndTestDataTransferRequest()
        {
        }
        
        public EndTestDataTransferRequest(ServiceReference1.EndTestDataTransferRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EndTestDataTransferRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataString;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int type;
        
        public EndTestDataTransferRequestBody()
        {
        }
        
        public EndTestDataTransferRequestBody(string dataString, int type)
        {
            this.dataString = dataString;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EndTestDataTransferResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EndTestDataTransferResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.EndTestDataTransferResponseBody Body;
        
        public EndTestDataTransferResponse()
        {
        }
        
        public EndTestDataTransferResponse(ServiceReference1.EndTestDataTransferResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EndTestDataTransferResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo EndTestDataTransferResult;
        
        public EndTestDataTransferResponseBody()
        {
        }
        
        public EndTestDataTransferResponseBody(ServiceReference1.APIBackInfo EndTestDataTransferResult)
        {
            this.EndTestDataTransferResult = EndTestDataTransferResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondSensorIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondSensorId", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.BondSensorIdRequestBody Body;
        
        public BondSensorIdRequest()
        {
        }
        
        public BondSensorIdRequest(ServiceReference1.BondSensorIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondSensorIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sensorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedure;
        
        public BondSensorIdRequestBody()
        {
        }
        
        public BondSensorIdRequestBody(string sn, string sensorId, string procedure)
        {
            this.sn = sn;
            this.sensorId = sensorId;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BondSensorIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BondSensorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.BondSensorIdResponseBody Body;
        
        public BondSensorIdResponse()
        {
        }
        
        public BondSensorIdResponse(ServiceReference1.BondSensorIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BondSensorIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo BondSensorIdResult;
        
        public BondSensorIdResponseBody()
        {
        }
        
        public BondSensorIdResponseBody(ServiceReference1.APIBackInfo BondSensorIdResult)
        {
            this.BondSensorIdResult = BondSensorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidIsCompleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidIsComplete", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ValidIsCompleteRequestBody Body;
        
        public ValidIsCompleteRequest()
        {
        }
        
        public ValidIsCompleteRequest(ServiceReference1.ValidIsCompleteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidIsCompleteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sensorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string procedure;
        
        public ValidIsCompleteRequestBody()
        {
        }
        
        public ValidIsCompleteRequestBody(string sensorId, string procedure)
        {
            this.sensorId = sensorId;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidIsCompleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidIsCompleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ValidIsCompleteResponseBody Body;
        
        public ValidIsCompleteResponse()
        {
        }
        
        public ValidIsCompleteResponse(ServiceReference1.ValidIsCompleteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidIsCompleteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo ValidIsCompleteResult;
        
        public ValidIsCompleteResponseBody()
        {
        }
        
        public ValidIsCompleteResponseBody(ServiceReference1.APIBackInfo ValidIsCompleteResult)
        {
            this.ValidIsCompleteResult = ValidIsCompleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidIsCompleteNewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidIsCompleteNew", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ValidIsCompleteNewRequestBody Body;
        
        public ValidIsCompleteNewRequest()
        {
        }
        
        public ValidIsCompleteNewRequest(ServiceReference1.ValidIsCompleteNewRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidIsCompleteNewRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sensorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string procedure;
        
        public ValidIsCompleteNewRequestBody()
        {
        }
        
        public ValidIsCompleteNewRequestBody(string sensorId, string procedure)
        {
            this.sensorId = sensorId;
            this.procedure = procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidIsCompleteNewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidIsCompleteNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ValidIsCompleteNewResponseBody Body;
        
        public ValidIsCompleteNewResponse()
        {
        }
        
        public ValidIsCompleteNewResponse(ServiceReference1.ValidIsCompleteNewResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidIsCompleteNewResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo ValidIsCompleteNewResult;
        
        public ValidIsCompleteNewResponseBody()
        {
        }
        
        public ValidIsCompleteNewResponseBody(ServiceReference1.APIBackInfo ValidIsCompleteNewResult)
        {
            this.ValidIsCompleteNewResult = ValidIsCompleteNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDataStorageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDataStorage", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.TestDataStorageRequestBody Body;
        
        public TestDataStorageRequest()
        {
        }
        
        public TestDataStorageRequest(ServiceReference1.TestDataStorageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataStorageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sensorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string procedure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string finallyResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string badCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string equipmentId;
        
        public TestDataStorageRequestBody()
        {
        }
        
        public TestDataStorageRequestBody(string testData, string sensorId, string procedure, string finallyResult, string badCode, string equipmentId)
        {
            this.testData = testData;
            this.sensorId = sensorId;
            this.procedure = procedure;
            this.finallyResult = finallyResult;
            this.badCode = badCode;
            this.equipmentId = equipmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDataStorageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDataStorageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.TestDataStorageResponseBody Body;
        
        public TestDataStorageResponse()
        {
        }
        
        public TestDataStorageResponse(ServiceReference1.TestDataStorageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataStorageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo TestDataStorageResult;
        
        public TestDataStorageResponseBody()
        {
        }
        
        public TestDataStorageResponseBody(ServiceReference1.APIBackInfo TestDataStorageResult)
        {
            this.TestDataStorageResult = TestDataStorageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDataStorageTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDataStorageTest", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.TestDataStorageTestRequestBody Body;
        
        public TestDataStorageTestRequest()
        {
        }
        
        public TestDataStorageTestRequest(ServiceReference1.TestDataStorageTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataStorageTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testData;
        
        public TestDataStorageTestRequestBody()
        {
        }
        
        public TestDataStorageTestRequestBody(string testData)
        {
            this.testData = testData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDataStorageTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDataStorageTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.TestDataStorageTestResponseBody Body;
        
        public TestDataStorageTestResponse()
        {
        }
        
        public TestDataStorageTestResponse(ServiceReference1.TestDataStorageTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDataStorageTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo TestDataStorageTestResult;
        
        public TestDataStorageTestResponseBody()
        {
        }
        
        public TestDataStorageTestResponseBody(ServiceReference1.APIBackInfo TestDataStorageTestResult)
        {
            this.TestDataStorageTestResult = TestDataStorageTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCraftInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCraftInfo", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetCraftInfoRequestBody Body;
        
        public GetCraftInfoRequest()
        {
        }
        
        public GetCraftInfoRequest(ServiceReference1.GetCraftInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCraftInfoRequestBody
    {
        
        public GetCraftInfoRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCraftInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCraftInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetCraftInfoResponseBody Body;
        
        public GetCraftInfoResponse()
        {
        }
        
        public GetCraftInfoResponse(ServiceReference1.GetCraftInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCraftInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.APIBackInfo GetCraftInfoResult;
        
        public GetCraftInfoResponseBody()
        {
        }
        
        public GetCraftInfoResponseBody(ServiceReference1.APIBackInfo GetCraftInfoResult)
        {
            this.GetCraftInfoResult = GetCraftInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TestDataCollectionSoapChannel : ServiceReference1.TestDataCollectionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TestDataCollectionSoapClient : System.ServiceModel.ClientBase<ServiceReference1.TestDataCollectionSoap>, ServiceReference1.TestDataCollectionSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TestDataCollectionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TestDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), TestDataCollectionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestDataCollectionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TestDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestDataCollectionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TestDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TestDataCollectionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.HelloWorldResponse> ServiceReference1.TestDataCollectionSoap.HelloWorldAsync(ServiceReference1.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.HelloWorldResponse> HelloWorldAsync()
        {
            ServiceReference1.HelloWorldRequest inValue = new ServiceReference1.HelloWorldRequest();
            inValue.Body = new ServiceReference1.HelloWorldRequestBody();
            return ((ServiceReference1.TestDataCollectionSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.TestResponse> ServiceReference1.TestDataCollectionSoap.TestAsync(ServiceReference1.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TestResponse> TestAsync()
        {
            ServiceReference1.TestRequest inValue = new ServiceReference1.TestRequest();
            inValue.Body = new ServiceReference1.TestRequestBody();
            return ((ServiceReference1.TestDataCollectionSoap)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.BondLotNoAndSnResponse> ServiceReference1.TestDataCollectionSoap.BondLotNoAndSnAsync(ServiceReference1.BondLotNoAndSnRequest request)
        {
            return base.Channel.BondLotNoAndSnAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BondLotNoAndSnResponse> BondLotNoAndSnAsync(string lotNo, string sn, string procedure)
        {
            ServiceReference1.BondLotNoAndSnRequest inValue = new ServiceReference1.BondLotNoAndSnRequest();
            inValue.Body = new ServiceReference1.BondLotNoAndSnRequestBody();
            inValue.Body.lotNo = lotNo;
            inValue.Body.sn = sn;
            inValue.Body.procedure = procedure;
            return ((ServiceReference1.TestDataCollectionSoap)(this)).BondLotNoAndSnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.BondLotNoAndSnOldResponse> ServiceReference1.TestDataCollectionSoap.BondLotNoAndSnOldAsync(ServiceReference1.BondLotNoAndSnOldRequest request)
        {
            return base.Channel.BondLotNoAndSnOldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BondLotNoAndSnOldResponse> BondLotNoAndSnOldAsync(string lotNo, string sn, string procedure)
        {
            ServiceReference1.BondLotNoAndSnOldRequest inValue = new ServiceReference1.BondLotNoAndSnOldRequest();
            inValue.Body = new ServiceReference1.BondLotNoAndSnOldRequestBody();
            inValue.Body.lotNo = lotNo;
            inValue.Body.sn = sn;
            inValue.Body.procedure = procedure;
            return ((ServiceReference1.TestDataCollectionSoap)(this)).BondLotNoAndSnOldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.EndTestDataTransferResponse> ServiceReference1.TestDataCollectionSoap.EndTestDataTransferAsync(ServiceReference1.EndTestDataTransferRequest request)
        {
            return base.Channel.EndTestDataTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EndTestDataTransferResponse> EndTestDataTransferAsync(string dataString, int type)
        {
            ServiceReference1.EndTestDataTransferRequest inValue = new ServiceReference1.EndTestDataTransferRequest();
            inValue.Body = new ServiceReference1.EndTestDataTransferRequestBody();
            inValue.Body.dataString = dataString;
            inValue.Body.type = type;
            return ((ServiceReference1.TestDataCollectionSoap)(this)).EndTestDataTransferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.BondSensorIdResponse> ServiceReference1.TestDataCollectionSoap.BondSensorIdAsync(ServiceReference1.BondSensorIdRequest request)
        {
            return base.Channel.BondSensorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BondSensorIdResponse> BondSensorIdAsync(string sn, string sensorId, string procedure)
        {
            ServiceReference1.BondSensorIdRequest inValue = new ServiceReference1.BondSensorIdRequest();
            inValue.Body = new ServiceReference1.BondSensorIdRequestBody();
            inValue.Body.sn = sn;
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            return ((ServiceReference1.TestDataCollectionSoap)(this)).BondSensorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ValidIsCompleteResponse> ServiceReference1.TestDataCollectionSoap.ValidIsCompleteAsync(ServiceReference1.ValidIsCompleteRequest request)
        {
            return base.Channel.ValidIsCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ValidIsCompleteResponse> ValidIsCompleteAsync(string sensorId, string procedure)
        {
            ServiceReference1.ValidIsCompleteRequest inValue = new ServiceReference1.ValidIsCompleteRequest();
            inValue.Body = new ServiceReference1.ValidIsCompleteRequestBody();
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            return ((ServiceReference1.TestDataCollectionSoap)(this)).ValidIsCompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ValidIsCompleteNewResponse> ServiceReference1.TestDataCollectionSoap.ValidIsCompleteNewAsync(ServiceReference1.ValidIsCompleteNewRequest request)
        {
            return base.Channel.ValidIsCompleteNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ValidIsCompleteNewResponse> ValidIsCompleteNewAsync(string sensorId, string procedure)
        {
            ServiceReference1.ValidIsCompleteNewRequest inValue = new ServiceReference1.ValidIsCompleteNewRequest();
            inValue.Body = new ServiceReference1.ValidIsCompleteNewRequestBody();
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            return ((ServiceReference1.TestDataCollectionSoap)(this)).ValidIsCompleteNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.TestDataStorageResponse> ServiceReference1.TestDataCollectionSoap.TestDataStorageAsync(ServiceReference1.TestDataStorageRequest request)
        {
            return base.Channel.TestDataStorageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TestDataStorageResponse> TestDataStorageAsync(string testData, string sensorId, string procedure, string finallyResult, string badCode, string equipmentId)
        {
            ServiceReference1.TestDataStorageRequest inValue = new ServiceReference1.TestDataStorageRequest();
            inValue.Body = new ServiceReference1.TestDataStorageRequestBody();
            inValue.Body.testData = testData;
            inValue.Body.sensorId = sensorId;
            inValue.Body.procedure = procedure;
            inValue.Body.finallyResult = finallyResult;
            inValue.Body.badCode = badCode;
            inValue.Body.equipmentId = equipmentId;
            return ((ServiceReference1.TestDataCollectionSoap)(this)).TestDataStorageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.TestDataStorageTestResponse> ServiceReference1.TestDataCollectionSoap.TestDataStorageTestAsync(ServiceReference1.TestDataStorageTestRequest request)
        {
            return base.Channel.TestDataStorageTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TestDataStorageTestResponse> TestDataStorageTestAsync(string testData)
        {
            ServiceReference1.TestDataStorageTestRequest inValue = new ServiceReference1.TestDataStorageTestRequest();
            inValue.Body = new ServiceReference1.TestDataStorageTestRequestBody();
            inValue.Body.testData = testData;
            return ((ServiceReference1.TestDataCollectionSoap)(this)).TestDataStorageTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetCraftInfoResponse> ServiceReference1.TestDataCollectionSoap.GetCraftInfoAsync(ServiceReference1.GetCraftInfoRequest request)
        {
            return base.Channel.GetCraftInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetCraftInfoResponse> GetCraftInfoAsync()
        {
            ServiceReference1.GetCraftInfoRequest inValue = new ServiceReference1.GetCraftInfoRequest();
            inValue.Body = new ServiceReference1.GetCraftInfoRequestBody();
            return ((ServiceReference1.TestDataCollectionSoap)(this)).GetCraftInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TestDataCollectionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TestDataCollectionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TestDataCollectionSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://sfc.nnmz.aacoptics.com:8888/WebService/TestDataCollection.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TestDataCollectionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://sfc.nnmz.aacoptics.com:8888/WebService/TestDataCollection.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TestDataCollectionSoap,
            
            TestDataCollectionSoap12,
        }
    }
}
